#!/usr/bin/env python3
"""Regenerate `src/randomize/cosmetic/palette_variants.rs` from the vanilla ROM
and the Recolored IPS.

The file is fully generated, so regenerating loses nothing; don't hand-edit it.
Hue families like "tuscan" are not stored here: they are a per-byte remap of
vanilla, applied at runtime in `palettes.rs` to a whole palette set.

Layout (verified against the ROM, see docs/smb3_rom_reference.md → "Palette
Sets"): the 16 `PalSet_*` sets of PRG027 sit back to back from 0x36BE2, 192
bytes each, and every 4-byte sub-palette starts at 0x36BE2 + 4n. The player
palette tables after `Palette_By_Tileset` are wardrobe, not world colors: the
player-color scheme in `palettes.rs` owns them.

For each aligned quartet in a region:
  - Recolored changed it → a VariantGroup: `[vanilla, Recolored]`, always in
    that order (the index is the source `palettes.rs` rolls per set);
  - Recolored kept it, but it holds a chromatic byte → ROTATE_ONLY_QUARTETS
    (never swapped, but hue-rotated with its theme so it can't clash).

Never covered:
  - 0x377E2-0x37807 `Palette_By_Tileset` — painting it crashes the loader.
  - 0x37808-0x3784E the player palette tables (bonus game, map suits) and
    `InitPal_Per_MapPowerup`, palette INDICES (00-08) that hue rotation would
    corrupt.
  - 0x3784F+ `Setup_PalData` code.
  - 0x33046-0x335xx — Recolored restructured this stream (insertions).

Usage:
    nix-shell -p python3 --run "python3 tools/gen_palette_variants.py"
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROM = ROOT / "roms/Super Mario Bros. 3 (USA) (Rev 1).nes"
IPS = ROOT / "patches/Super Mario Bros. 3 Recolored v1.0.ips"
OUT = ROOT / "src/randomize/cosmetic/palette_variants.rs"

PALSET_BASE = 0x36BE2
PALSET_SIZE = 0xC0

# (rust_const_name, label) for each PalSet, in ROM order.
PALSETS = [
    ("MAPS_VARIANTS", "PalSet_Maps (tileset 0: world map)"),
    ("PLAINS_VARIANTS", "PalSet_Plains (tileset 1)"),
    ("FORT_VARIANTS", "PalSet_Fort (tileset 2)"),
    ("HILLS_UNDER_VARIANTS", "PalSet_HillsUnder (tilesets 3, 14)"),
    ("HIGH_UP_VARIANTS", "PalSet_HighUp (tileset 4)"),
    ("PLANT_VARIANTS", "PalSet_Plant (tileset 5)"),
    ("WATER_VARIANTS", "PalSet_Water (tileset 6)"),
    ("TOAD_VARIANTS", "PalSet_Toad (tileset 7)"),
    ("PIPE_MAZE_VARIANTS", "PalSet_PipeMaze (tileset 8)"),
    ("DESERT_VARIANTS", "PalSet_Desert (tileset 9)"),
    ("AIRSHIP_VARIANTS", "PalSet_Airship (tileset 10)"),
    ("GIANT_VARIANTS", "PalSet_Giant (tileset 11)"),
    ("ICE_VARIANTS", "PalSet_Ice (tileset 12)"),
    ("SKY_VARIANTS", "PalSet_Sky (tileset 13)"),
    ("TWO_P_VS_VARIANTS", "PalSet_2PVs (tileset 18)"),
    ("BONUS_VARIANTS", "PalSet_Bonus (tilesets 15-17)"),
]

# (rust_const_name, label, start, end) — every region, each on its own grid.
REGIONS = [
    (name, label, PALSET_BASE + i * PALSET_SIZE, PALSET_BASE + (i + 1) * PALSET_SIZE)
    for i, (name, label) in enumerate(PALSETS)
]


def parse_ips(p):
    d = p.read_bytes()
    assert d[:5] == b"PATCH"
    pos = 5
    out = []
    while d[pos : pos + 3] != b"EOF":
        off = (d[pos] << 16) | (d[pos + 1] << 8) | d[pos + 2]
        pos += 3
        sz = (d[pos] << 8) | d[pos + 1]
        pos += 2
        if sz == 0:
            n = (d[pos] << 8) | d[pos + 1]
            v = d[pos + 2]
            pos += 3
            out.append((off, bytes([v]) * n))
        else:
            out.append((off, d[pos : pos + sz]))
            pos += sz
    return out


def is_chromatic(b):
    return b <= 0x3C and 1 <= (b & 0x0F) <= 0x0C


def hexq(q):
    return ", ".join(f"0x{b:02X}" for b in q)


HEADER = """\
//! Curated palette-group variants for themed palette randomization.
//!
//! GENERATED by `tools/gen_palette_variants.py` — do not hand-edit; change the
//! generator and rerun it. Every variant derives byte-for-byte from the vanilla
//! ROM or the "Super Mario Bros. 3 Recolored v1.0" IPS, so a regeneration loses
//! nothing.
//!
//! Each entry is one 4-color sub-palette (file offset) that Recolored changed,
//! as `[vanilla, Recolored]` in that order. `palettes.rs` rolls one source per
//! palette set and uses it for every sub-palette in the set, so a screen is
//! always one designed scheme.
//!
//! Layout: one table per `PalSet_*` set of PRG027 (192 bytes each from 0x36BE2;
//! sub-palettes start at 0x36BE2 + 4n). See `docs/smb3_rom_reference.md` →
//! "Palette Sets". Never covered: `Palette_By_Tileset` (0x377E2-0x37807,
//! painting it crashes the loader), and the player palette tables after it,
//! which belong to the player-color scheme in `palettes.rs`.
//!
//! Every table carries `#[rustfmt::skip]`: the compact four-line-per-group
//! layout is what keeps a palette table readable, and what `git diff` after a
//! regeneration is meant to show.

/// A sub-palette Recolored changed, at a specific file offset.
pub(crate) struct VariantGroup {
    pub(crate) offset: usize,
    /// `[vanilla, Recolored]`, always in that order.
    pub(crate) variants: &'static [[u8; 4]],
}
"""


def main():
    vanilla = ROM.read_bytes()
    recolored = bytearray(vanilla)
    for off, payload in parse_ips(IPS):
        recolored[off : off + len(payload)] = payload

    out = [HEADER]
    p = out.append
    rotate_only = []  # (label, [offsets])
    for const_name, label, start, end in REGIONS:
        assert (end - start) % 4 == 0, const_name
        groups = []
        kept = []
        for off in range(start, end, 4):
            v = bytes(vanilla[off : off + 4])
            r = bytes(recolored[off : off + 4])
            if v != r:
                groups.append((off, [(v, "vanilla"), (r, "recolored")]))
            elif any(is_chromatic(b) for b in v):
                kept.append(off)
        rotate_only.append((label, kept))

        p("// " + "-" * 74)
        p(f"// {label}: {start:#07x}-{end - 1:#07x}")
        p(f"// {len(groups)} sub-palettes changed by Recolored.")
        p("// " + "-" * 74)
        p("")
        p("#[rustfmt::skip]")
        p(f"pub(crate) const {const_name}: &[VariantGroup] = &[")
        for off, variants in groups:
            p(f"    VariantGroup {{ offset: 0x{off:05X}, variants: &[")
            for q, lab in variants:
                p(f"        [{hexq(q)}],  // {lab}")
            p("    ]},")
        p("];")
        p("")

    p("// " + "-" * 74)
    p("// Rotate-only quartets: sub-palettes Recolored left at vanilla that hold")
    p("// chromatic bytes. Never variant-swapped, but hue-rotated with their theme")
    p("// group so a kept-vanilla green can't clash with rotated neighbours.")
    p("// " + "-" * 74)
    p("")
    p("#[rustfmt::skip]")
    p("pub(crate) const ROTATE_ONLY_QUARTETS: &[usize] = &[")
    for label, offs in rotate_only:
        if not offs:
            continue
        p(f"    // {label} ({len(offs)})")
        for i in range(0, len(offs), 8):
            p("    " + " ".join(f"0x{o:05X}," for o in offs[i : i + 8]))
    p("];")

    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
